# Production configuration - maximum accuracy
# Override: python train.py --config-name production

defaults:
  - train
  - _self_

# Production dataset configuration
data:
  mix_real_ratio: 0.2               # More synthetic for diversity
  mix_synth_ratio: 0.8
  image_size: 512                   # Larger for production
  initial_size: 384
  num_workers: 16

# Enable all preprocessing
text_removal:
  enabled: true

synthetic:
  enabled: true
  num_images: 15000                 # Maximum diversity

# Enable DINOv2 warm-up for +3-5% accuracy
dinov2:
  enabled: true
  epochs: 100

# Best model configuration
model:
  backbone: "convnextv2_nano.fcmae_ft_in22k_in1k_384"
  head: "arcface"
  scale: 30.0
  margin: 0.5

# Extended training
training:
  epochs: 120
  batch_size: 32                    # Larger batches for stability
  gradient_accumulation_steps: 2    # Effective batch size = 64

  progressive_resize:
    enabled: true
    schedule:
      - [0, 384]
      - [40, 448]
      - [80, 512]

  early_stopping:
    enabled: true
    patience: 25                    # More patience for production

# Full TTA for validation
augmentation:
  tta:
    enabled: true
    num_augmentations: 16           # Maximum TTA

# Production logging
logging:
  wandb:
    enabled: true
    log_model: "all"
  tensorboard:
    enabled: true
  log_every_n_steps: 25

# Production export
export:
  onnx:
    enabled: true
    simplify: true
  tensorrt:
    enabled: true
    fp16: true
    int8: false                     # Set to true if you have calibration data

hardware:
  devices: 1
  benchmark: true
  deterministic: false              # Max speed in production
